[*]
# Global defaults
ngl = 999
no-mmap = 1
mlock = 1
ctx-size = 100000
jinja = 1
; batch-size = 2048
; ubatch-size = 512
; flash-attn = on
; np = 1
threads = 6
ctk = q4_0
ctv = q4_0
; spec-type = ngram-mod
; spec-ngram-mod-n-match = 24
; spec-ngram-mod-n-min = 12
; spec-ngram-mod-n-max = 48
cache-reuse = 256
metrics = 1
n-predict = 32000
reasoning = off

[qwen36-reap-28b-a3b-barozp]
model = /home/user/aimodels/llms/Qwen3.6-28B-REAP20-A3B-Q4_K_M.barozp.gguf
alias = qwen36-reap-28b-a3b-barozp
n-cpu-moe = 33