/home/$USER/agi/llama.cpp/build/bin/llama-server \
    --model /home/user/aimodels/llms/Qwen_Qwen3.6-35B-A3B-IQ4_NL.bartowski.gguf \
    --n-cpu-moe 35 \
    --temp 1.0 \
    --top-p 0.95 \
    --top-k 20 \
    --min-p 0.0 \
    --presence-penalty 0.0 \
    --repeat-penalty 1.0 \
    --reasoning on \
    --reasoning-preserve \
    --reasoning-budget 6000 \
    --reasoning-budget-message "\nOkay, I have enough information to answer." \
    --n-gpu-layers 999 \
    --mlock \
    --no-mmap \
    --ctx-size 80000 \
    --jinja \
    --batch-size 2048 \
    --ubatch-size 512 \
    --flash-attn on \
    --parallel 1 \
    --threads 14 \
    --cache-type-k q4_0 \
    --cache-type-v q4_0 \
    --host 0.0.0.0 \
    --port 8080
