/home/$USER/agi/llama.cpp/build/bin/llama-server \
    --model /home/user/aimodels/llms/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf \
    --host 0.0.0.0 \
    --port 8080 \
    --reasoning on \
    --reasoning-preserve \
    --mlock \
    --no-mmap \
    --ctx-size 32768 \
    --jinja \
    --batch-size 2048 \
    --ubatch-size 512 \
    --flash-attn on \
    --parallel 1 \
    --threads 14 \
    --cache-type-k q8_0 \
    --cache-type-v q8_0 \
    --temp 0.6 \
    --top-p 0.95 \
    --top-k 20 \
    --min-p 0.0 \
    --presence-penalty 0.0 \
    --repeat-penalty 1.0 \
    --n-gpu-layers 999 