/home/$USER/agi/llama.cpp/build/bin/llama-server \
    --model /home/user/aimodels/llms/gemma-4-26B-A4B-it-qat-UD-Q4_K_XL.unsloth.gguf \
    --n-cpu-moe 23 \
    --temp 1.0 \
    --top-p 0.95 \
    --top-k 64 \
    --chat-template-kwargs '{"enable_thinking":true}' \
    --n-gpu-layers 999 \
    --mlock \
    --no-mmap \
    --ctx-size 80000 \
    --jinja \
    --batch-size 2048 \
    --ubatch-size 512 \
    --flash-attn on \
    --parallel 1 \
    --threads 14 \
    --cache-type-k q4_0 \
    --cache-type-v q4_0 \
    --host 0.0.0.0 \
    --port 8080
