/home/$USER/agi/llama.cpp/build/bin/llama-server \
    --model /home/user/aimodels/llms/Qwen_Qwen3.6-35B-A3B-IQ4_NL.bartowski.gguf \
    --model-draft /home/user/aimodels/llms/mtp-Qwen_Qwen3.6-35B-A3B-Q4_0.bartowski.gguf \
    --spec-type draft-mtp \
    --spec-draft-n-max 2 \
    --n-cpu-moe 38 \
    --temp 0.6 \
    --top-p 0.95 \
    --top-k 20 \
    --min-p 0.0 \
    --presence-penalty 0.0 \
    --repeat-penalty 1.0 \
    --chat-template-kwargs '{"preserve_thinking": true}' \
    --n-gpu-layers 999 \
    --mlock \
    --no-mmap \
    --ctx-size 80000 \
    --jinja \
    --batch-size 2048 \
    --ubatch-size 512 \
    --flash-attn on \
    --parallel 1 \
    --threads 14 \
    --cache-type-k q4_0 \
    --cache-type-v q4_0 \
    --host 0.0.0.0 \
    --port 8080
